services:
  flask-upload:
    build: .
    container_name: sdr_upload_server
    restart: unless-stopped
    ports:
      # Mapeia a porta de API (ex: 8080 no host -> 5000 no container)
      - "${HOST_PORT}:${CONTAINER_PORT}"
      # Mapeia a porta WEB (ex: 80 no host -> 5000 no container)
      - "${HOST_PORT_WEB}:${CONTAINER_PORT}"
    volumes:
      - "${UPLOAD_DIR_HOST}:${UPLOAD_DIR_CONTAINER}"
      - "${DOWNLOAD_DIR_HOST}:${DOWNLOAD_DIR_CONTAINER}"
    environment:
      - CONTAINER_PORT=${CONTAINER_PORT}
      - UPLOAD_DIR_CONTAINER=${UPLOAD_DIR_CONTAINER}
      - DOWNLOAD_DIR_CONTAINER=${DOWNLOAD_DIR_CONTAINER}